### ISSUE TITLE
Dependency Requirement: libsoup  (also, Gnome & multimedia keys?)

### ISSUE THREAD

**Issue by carakesa** [mavit/slimpris2#21]
Building from source or installing from the Arch AUR will appear successful but fail with

```
╰─❯ slimpris2
Traceback (most recent call last):
  File "/usr/sbin/slimpris2", line 50, in <module>
    gi.require_version('Soup', '2.4')
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 125, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Soup not available for version 2.4
```

Simply installing libsoup allows it to run and I can interact via Playerctl 

Just for info in case someone else needs it:  

Since I'm not using Gnome, I do get this message as well: 

```
2024-09-08 18:38:57,561 slimpris2 ERROR: Failed to connect to GNOME Settings Daemon. Disabling multimedia key support
```

**Comment by mavit** [comment]
This is best handled in the AUR packaging.

@snakeroot: Do you want to take a look?

**Comment by carakesa** [comment]
To add: it appears to be a dependency across the board, so even building
from source (and/or from the AUR) it will compile but can't run without
libsoup

**Comment by mavit** [comment]
> To add: it appears to be a dependency across the board, so even building from source (and/or from the AUR) it will compile but can't run without libsoup

Indeed.  Soup is only required at run-time, not build time, which is why it isn't checked for at build time.  When building a package, the build machine and the install machine aren't the same, so won't have the same things installed.

**Comment by snakeroot** [comment]
> This is best handled in the AUR packaging.
> 
> @snakeroot: Do you want to take a look?

It seems I could either add it as a dependency or as a local dependency in the package( ) function. While the former may not be technically correct, it is straightforward and I doubt there are many people building the package on (libsoupless) machine A for installation on machine B.

https://gitlab.archlinux.org/pacman/pacman/-/issues/22

Let me know your thoughts, and I'll take care of it at the weekend.

**Comment by mavit** [comment]
@snakeroot: I don't know anything about Arch packages, but had naïvely assumed you could simply add `libsoup` to the `depends=` section that already contains the other runtime dependencies.  I'll leave it to your judgment. 

Thanks for packaging this, by the way!

**Comment by mavit** [comment]
Looks like this was fixed in [version 3.1.2-1 of the AUR package](https://aur.archlinux.org/cgit/aur.git/commit/?h=slimpris2&id=011a2a232970078b6c530a9cfe4375bec6c654fc).
